# Torchlight stark theme for Alacritty
# Features an almost black background for maximum contrast
[colors.bright]
black = "#575547"
white = "#E8D2A9"
blue = "#848A68"
cyan = "#799173"
green = "#979764"
magenta = "#D97E4A"
red = "#D0654B"
yellow = "#E3A138"

[colors.dim]
black = "#0d0d0d"
white = "#E3CA9A"
blue = "#848A68"
cyan = "#799173"
green = "#979764"
magenta = "#D97E4A"
red = "#D0654B"
yellow = "#E3A138"

[colors.normal]
black = "#0d0d0d"
white = "#E3CA9A"
blue = "#848A68"
cyan = "#799173"
green = "#979764"
magenta = "#D97E4A"
red = "#D0654B"
yellow = "#E3A138"

[colors.primary]
background = "#0d0d0d"
bright_foreground = "#E8D2A9"
foreground = "#E3CA9A"
